import { Condition } from '../../types';

export const oabCondition: Condition = {
  id: 'oab',
  name: 'Overactive Bladder (OAB)',
  treatments: [
    // ── First-Line Behavioral ──
    {
      id: 'oab-bladder-diary',
      name: 'Bladder Diary',
      tier: 'first-line',
      category: 'Behavioral',
      defaultDuration: '2 weeks',
      doseOptions: [],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-fluid-management',
      name: 'Fluid Management',
      tier: 'first-line',
      category: 'Behavioral',
      defaultDuration: 'Ongoing',
      doseOptions: [],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-caffeine-reduction',
      name: 'Caffeine Reduction',
      tier: 'first-line',
      category: 'Behavioral',
      defaultDuration: 'Ongoing',
      doseOptions: [],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-timed-voiding',
      name: 'Timed Voiding',
      tier: 'first-line',
      category: 'Behavioral',
      defaultDuration: '4-6 weeks',
      doseOptions: [],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-bladder-training',
      name: 'Bladder Training',
      tier: 'first-line',
      category: 'Behavioral',
      defaultDuration: '6-8 weeks',
      doseOptions: [],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-pelvic-floor-exercises',
      name: 'Pelvic Floor Muscle Exercises (Kegels)',
      tier: 'first-line',
      category: 'Behavioral',
      defaultDuration: '6-8 weeks',
      doseOptions: [],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-urge-suppression',
      name: 'Urge Suppression Techniques',
      tier: 'first-line',
      category: 'Behavioral',
      defaultDuration: '4-6 weeks',
      doseOptions: [],
      requiresProvider: false,
      pdfHandoutPath: null,
    },

    // ── Second-Line Pharmacotherapy: Beta-3 Agonists ──
    {
      id: 'oab-vibegron-75mg',
      name: 'Vibegron 75 mg',
      tier: 'second-line',
      category: 'Beta-3 Agonist',
      defaultDuration: '4-6 weeks',
      doseOptions: ['75 mg daily'],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-mirabegron-25mg',
      name: 'Mirabegron 25 mg',
      tier: 'second-line',
      category: 'Beta-3 Agonist',
      defaultDuration: '4-6 weeks',
      doseOptions: ['25 mg daily'],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-mirabegron-50mg',
      name: 'Mirabegron 50 mg',
      tier: 'second-line',
      category: 'Beta-3 Agonist',
      defaultDuration: '4-6 weeks',
      doseOptions: ['50 mg daily'],
      requiresProvider: false,
      pdfHandoutPath: null,
    },

    // ── Second-Line Pharmacotherapy: Antimuscarinics ──
    {
      id: 'oab-oxybutynin-ir-5mg',
      name: 'Oxybutynin IR 5 mg',
      tier: 'second-line',
      category: 'Antimuscarinic',
      defaultDuration: '4-6 weeks',
      doseOptions: ['5 mg twice daily', '5 mg three times daily'],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-oxybutynin-er-5mg',
      name: 'Oxybutynin ER 5 mg',
      tier: 'second-line',
      category: 'Antimuscarinic',
      defaultDuration: '4-6 weeks',
      doseOptions: ['5 mg daily', '10 mg daily', '15 mg daily'],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-tolterodine-ir-2mg',
      name: 'Tolterodine IR 2 mg',
      tier: 'second-line',
      category: 'Antimuscarinic',
      defaultDuration: '4-6 weeks',
      doseOptions: ['2 mg twice daily'],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-tolterodine-er-4mg',
      name: 'Tolterodine ER 4 mg',
      tier: 'second-line',
      category: 'Antimuscarinic',
      defaultDuration: '4-6 weeks',
      doseOptions: ['4 mg daily'],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-solifenacin-5mg',
      name: 'Solifenacin 5 mg',
      tier: 'second-line',
      category: 'Antimuscarinic',
      defaultDuration: '4-6 weeks',
      doseOptions: ['5 mg daily', '10 mg daily'],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-darifenacin-7-5mg',
      name: 'Darifenacin 7.5 mg',
      tier: 'second-line',
      category: 'Antimuscarinic',
      defaultDuration: '4-6 weeks',
      doseOptions: ['7.5 mg daily', '15 mg daily'],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-fesoterodine-4mg',
      name: 'Fesoterodine 4 mg',
      tier: 'second-line',
      category: 'Antimuscarinic',
      defaultDuration: '4-6 weeks',
      doseOptions: ['4 mg daily', '8 mg daily'],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-trospium-20mg',
      name: 'Trospium 20 mg',
      tier: 'second-line',
      category: 'Antimuscarinic',
      defaultDuration: '4-6 weeks',
      doseOptions: ['20 mg twice daily'],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-trospium-er-60mg',
      name: 'Trospium ER 60 mg',
      tier: 'second-line',
      category: 'Antimuscarinic',
      defaultDuration: '4-6 weeks',
      doseOptions: ['60 mg daily'],
      requiresProvider: false,
      pdfHandoutPath: null,
    },

    // ── Second-Line Pharmacotherapy: Combination ──
    {
      id: 'oab-vibegron-mirabegron-combo',
      name: 'Vibegron + Antimuscarinic Combination',
      tier: 'second-line',
      category: 'Combination Therapy',
      defaultDuration: '4-6 weeks',
      doseOptions: ['Vibegron 75 mg + antimuscarinic per prescriber'],
      requiresProvider: false,
      pdfHandoutPath: null,
    },

    // ── Second-Line Pharmacotherapy: Topical Estrogen ──
    {
      id: 'oab-topical-estrogen',
      name: 'Topical Vaginal Estrogen',
      tier: 'second-line',
      category: 'Topical Estrogen',
      defaultDuration: 'Ongoing',
      doseOptions: ['Estradiol cream 0.5 g twice weekly', 'Estradiol ring every 3 months', 'Estradiol insert twice weekly'],
      requiresProvider: false,
      pdfHandoutPath: null,
    },

    // ── Third-Line Procedures ──
    {
      id: 'oab-botox',
      name: 'OnabotulinumtoxinA (Botox) Injection',
      tier: 'third-line',
      category: 'Procedure',
      defaultDuration: '6-9 months',
      doseOptions: ['100 units intradetrusor'],
      requiresProvider: true,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-ptns',
      name: 'Percutaneous Tibial Nerve Stimulation (PTNS)',
      tier: 'third-line',
      category: 'Procedure',
      defaultDuration: '12 weeks initial, then monthly',
      doseOptions: [],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-implantable-tibial',
      name: 'Implantable Tibial Nerve Stimulator',
      tier: 'third-line',
      category: 'Procedure',
      defaultDuration: 'Ongoing',
      doseOptions: [],
      requiresProvider: true,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-sacral-neuromodulation',
      name: 'Sacral Neuromodulation (InterStim)',
      tier: 'third-line',
      category: 'Procedure',
      defaultDuration: 'Ongoing',
      doseOptions: [],
      requiresProvider: true,
      pdfHandoutPath: null,
    },

    // ── Adjunctive ──
    {
      id: 'oab-pessary',
      name: 'Pessary',
      tier: 'adjunctive',
      category: 'Device',
      defaultDuration: 'Ongoing',
      doseOptions: [],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
    {
      id: 'oab-incontinence-products',
      name: 'Incontinence Products',
      tier: 'adjunctive',
      category: 'Supportive',
      defaultDuration: 'As needed',
      doseOptions: [],
      requiresProvider: false,
      pdfHandoutPath: null,
    },
  ],
};
